# This is a basic workflow to help you get started with Actions

name: Python Azure Functions workflow

# Controls when the action will run. 
on:
  # Triggers the workflow on push 
  [push, pull_request]

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: 'Azure_function/'   # the path to the web app project
  PYTHON_VERSION: '3.8'                 # (supports 3.6, 3.7, 3.8)

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains jobs "test" and "build"
  test-and-build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout GitHub Action
        uses: actions/checkout@v2
      
      - name: Setup Python ${{ env.PYTHON_VERSION }} Environment
        uses: actions/setup-python@v1
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      
      - name: Install Dependencies Using Pip
        shell: bash
        run: |
          pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
          python -m pip install --upgrade pip
          pip install -r requirements.txt --target=".python_packages/lib/site-packages"
          popd

      - name: Test with Pytest
        shell: bash
        run: |
          pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
          pip install pytest -r requirements.txt
          pytest
          popd
